// Code generated by goctl. DO NOT EDIT.
package types

import "time"

type (
	UnlockRequest struct {
		Words []string `json:"words"`
	}

	UnlockResult struct {
		InputWords      []string        `json:"input_words"`
		DetectedRoots   []CharacterRoot `json:"detected_roots"`
		RootCount       int             `json:"root_count"`
		UnlockableWords int             `json:"unlockable_words"`
		WordBreakdown   map[string]int  `json:"word_breakdown"`
		Insights        []string        `json:"insights"`
	}

	CharacterRoot struct {
		ID          int64  `json:"id"`
		Root        string `json:"root"`
		Pinyin      string `json:"pinyin"`
		Difficulty  int    `json:"difficulty"`
		Tier        int    `json:"tier"`
		Description string `json:"description"`
	}

	StartSessionRequest struct {
		UserID string `json:"user_id,omitempty"`
	}

	StartSessionResponse struct {
		SessionID string `json:"session_id"`
		StartTime string `json:"start_time"`
		Status    string `json:"status"`
		Message   string `json:"message"`
	}

	Level struct {
		ID          string   `json:"id"`
		Type        string   `json:"type"`
		Title       string   `json:"title"`
		Description string   `json:"description"`
		RootID      int64    `json:"root_id"`
		Difficulty  int      `json:"difficulty"`
		TimeLimit   int      `json:"time_limit"`
		Questions   []Question `json:"questions"`
		Reward      Reward   `json:"reward"`
	}

	Question struct {
		ID           string   `json:"id"`
		Type         string   `json:"type"`
		Content      string   `json:"content"`
		Options      []string `json:"options,omitempty"`
		CorrectAnswer string  `json:"correct_answer"`
		Hint         string   `json:"hint,omitempty"`
		Explanation  string   `json:"explanation"`
	}

	Reward struct {
		Roots      []int64 `json:"roots"`
		Score      int     `json:"score"`
		Achievement string `json:"achievement,omitempty"`
	}

	AnswerRequest struct {
		QuestionID string `json:"question_id"`
		Answer     string `json:"answer"`
	}

	AnswerResult struct {
		Correct     bool   `json:"correct"`
		Score       int    `json:"score"`
		Explanation string `json:"explanation"`
		NextHint    string `json:"next_hint,omitempty"`
	}

	TreasureMap struct {
		UserID       string                  `json:"user_id"`
		SessionID    string                  `json:"session_id"`
		Roots        []CharacterRoot         `json:"roots"`
		Vocabularies map[string][]Vocabulary `json:"vocabularies"`
		Connections  []Connection            `json:"connections"`
		Achievements []Achievement           `json:"achievements"`
		Stats        SessionStats            `json:"stats"`
	}

	Vocabulary struct {
		ID             int64  `json:"id"`
		RootID         int64  `json:"root_id"`
		Language       string `json:"language"`
		Word           string `json:"word"`
		Romaji         string `json:"romaji,omitempty"`
		Pronunciation  string `json:"pronunciation"`
		Meaning        string `json:"meaning"`
		ReadType       string `json:"read_type,omitempty"`
		Difficulty     int    `json:"difficulty"`
		ExampleCount   int    `json:"example_count"`
	}

	Connection struct {
		FromRootID  int64  `json:"from_root_id"`
		ToRootID    int64  `json:"to_root_id"`
		Type        string `json:"type"`
		Description string `json:"description"`
	}

	Achievement struct {
		ID          string    `json:"id"`
		Name        string    `json:"name"`
		Description string    `json:"description"`
		Icon        string    `json:"icon"`
		Condition   string    `json:"condition"`
		Reward      string    `json:"reward"`
		CreatedAt   time.Time `json:"created_at"`
	}

	SessionStats struct {
		TotalRoots     int     `json:"total_roots"`
		UnlockedRoots  int     `json:"unlocked_roots"`
		TotalWords     int     `json:"total_words"`
		LearnedWords   int     `json:"learned_words"`
		Accuracy       float64 `json:"accuracy"`
		AverageTime    int     `json:"average_time"`
		CompletionRate float64 `json:"completion_rate"`
	}

	RecommendationsResponse struct {
		RecommendedRoots []CharacterRoot `json:"recommended_roots"`
		Reason          string         `json:"reason"`
		NextGoals       []string       `json:"next_goals"`
	}

	// Additional types for handlers
	TreasureMapRequest struct {
		SessionID string `path:"sessionId"`
	}

	RecommendationsRequest struct {
		SessionID string `path:"sessionId"`
	}

	LevelRequest struct {
		LevelId string `path:"levelId"`
	}
)
